settings:
    nation-max-capacity: 50
    maximum-hotbar-name-length: 12
    main-world-name: "AvatarMap"
    secondary-world-name: "BuildWorld"

messages:
    nation-help:
      - "&7-----------= &bNation Commands &7=-----------"
      - "&e/nation help &7| &6Displays all available nation related commands."
      - "&e/nation nations/n &7| &6Lists all nations and their player count including number of rouges on server."
      - "&e/nation join/n &7| &6Attempts to join the nation associated with your first chosen element."
      - "&e/nation leave/n &7| &6Leave your current nation, giving up the rights to any plots and becoming a Rogue player."
      - "&7-----------= &bNation Commands &7=-----------"
    tribe-help:
      - "&7-----------= &bTribe Commands &7=-----------"
      - "&e/tribe help &7| &6Displays all available tribe related commands."
      - "&e/tribe show [tribe] &7| &6Displays tribe information such as the current players online, power, etc."
      - "&e/tribe create [name] &7| &6Create your own tribe with the specified name, if not taken."
      - "&e/tribe join [tribe] &7| &6Send a join request to the specified tribe. If you already have an invite from the tribe, this will accept the invite."
      - "&e/tribe invite [player] &7| &6Send a request to join your tribe to the specified player, if the player has already requested to join, this will accept their request."
      - "&e/tribe leave &7| &6Leave your current tribe, note that the owner cannot leave his tribe and must disband."
      - "&e/tribe home &7| &6Teleport to your tribe home if exists, otherwise to your tribe plot if claimed."
      - "&e/tribe promote [player] &7| &6Promote the specified player to officer rank, only tribe owners and officers can use this command."
      - "&e/tribe kick [player] &7| &6Kick the specified player from your tribe, only tribe owners and officers can use this command."
      - "&7-----------= &bTribe Commands &7=-----------"
    
    nation-show:
      - "&e------=== %nation% &e===------"
      - "&ePlayer Count: &7%players%&b/&750"
      - "&eOnline Players: &b[&a%online%&b]"
      - "&eOffline Players: &b[&c%offline%&b]"
      - "&eNation Leader Status: &b%leader%"
      
    tribe-show:
      - "&eTribe: &b%tribe%"
      - "&ePower: &c%tribepower%"
      - "&eClaim: &6%claimcount%&b/&6%maxclaimcount%"
      - "&ePlayer count: &7%playercount%&b/&7%maxplayercount%"
      - "&eOnline Players: &b[&a%online%&b]"
      - "&eOffline Players: &b[&c%offline%&b]"
      - "&eAllies: &b[&5%allies%&b]"
      
    teleportation-cancelled: "&cTeleportation canceled, you moved!"
    teleportation-cooldown: "&eTeleportation in 3 seconds..."
    invalid-permissions: "&cYou do not have permission to execute this command."
    tribe-leave: "&cYou have left the tribe %tribe%."
    tribe-leave-global: "&e%player% has abandoned the tribe."
    tribe-owner-leave: "&cYou can't leave your tribe since you are the leader."
    not-in-tribe: "&cYou are not a member of a tribe."
    tribe-not-exist: "&cThe specified tribe does not exist."
    nation-not-exist: "&cThe specified nation does not exist."
    already-in-tribe: "&cYou are already a part of a tribe."
    tribe-name-taken: "&cThis name is already taken by another tribe."
    tribe-name-long: "&cTribe name must be under 20 characters long."
    tribe-create: "&eYou have successfully created the tribe %tribe%, run /tribe help to see a list of commands."
    tribe-already-requested: "&cYou have already requested to join this tribe."
    tribe-request: "&eYou have requested to join the tribe %tribe%."
    tribe-request-global: "&e%player% has requested to join the tribe."
    tribe-join: "&eYou have joined the tribe &b%tribe%&e."
    tribe-join-global: "&b%player% &ehas joined the tribe! Make sure to give them a warm welcome."
    tribe-full: "&cThis tribe is at maximum capacity."
    tribe-officer-command: "&cYou must be the tribe leader or an officer to use this command."
    tribe-owner-command: "&cYou must be the tribe leader or the co-owner to use this command."
    tribe-permission-command: "&cYou must be a co-owner or owner of a tribe in order to promote members."
    target-not-online: "&cThe targetted player is either not online, or doesn't exist."
    target-not-in-tribe: "&cThe targetted player is not in your tribe."
    target-not-in-nation: "&cThe targetted player is a rogue player."
    target-in-tribe: "&cThe targetted player is already a part of a tribe."
    target-cannot-promote: "&cThe targetted player is already an officer, or is a leader and thus cannot be promoted."
    target-cannot-demote: "&cThe targetted player is already a default, or is a leader and thus cannot be demoted."
    target-cannot-kick: "&cThe targetted player is either an officer or the tribe leader and thus cannot be kicked."
    tribe-promote: "&aYou have successfully promoted %player% to &cOFFICER&e."
    tribe-promoted: "&aYou have been promoted to &cOFFICER &eby your tribe."
    tribe-promote-global: "&b%player% &ehas been promoted to &cOFFICER&e."
    tribe-demote: "&aYou have successfully demoted %player% to &cDEFAULT&e."
    tribe-demoted: "&aYou have been demoted to &cDEFAULT &eby your tribe."
    tribe-demote-global: "&b%player% &ehas been demoted to &cDEFAULT&e."   
    tribe-sethome: "&eThe home of your tribe has been defined."
    tribe-sethome-outside: "&cYou cannot set your tribe's home outside a claimed area!" 
    player-already-in-nation: "&cYou already have a nation!"
    player-already-invited: "&cThe targetted player already has a pending invite from your tribe."
    player-invited: "&eYou have been invited to join the &c%tribe% &etribe."
    player-invited-global: "&c%player% &ehas been invited to join the tribe."
    tribe-kick: "&aYou have successfully kicked &c%player% &afrom your tribe."
    tribe-kicked: "&cYou have been kicked from your tribe!"
    tribe-kick-global: "&c%player% &ehas been kicked from the tribe."
    tribe-disband-confirm: "&cWarning this can not be undone and you will lose any current plot rights! Type '&econfirm&c' in chat to disband your tribe. This will automatically expire in &e10 &cseconds."
    tribe-disband-global: "&eYour tribe has been &cDISBANDED &eby your tribe leader!"
    nation-show-invalid: "&cInvalid nation/player name."
    nation-leave: "&cWarning! You may only leave and join a nation 3 times, and you may only re-join &e%nation% &cnation! You cannot switch nations! Type &aconfirm &cto confirm this action."
    nation-leave-confirmed: "&aYou left the nation."
    nation-assigned: "&eYou have been assigned to the %nation% &enation!"
    nation-full: "&cThe specified nation does not have any room."
    nation-kick: "&cYou have kicked the target player from their nation!"
    nation-kicked: "&cYou have been kicked from &e%nation% &cnation for &e%reason%."
    nation-join: "&eYou have joined the %nation% &enation. (You may not switch nations)."
    nation-cannot-be-changed: "&eNation cannot be changed. You have chosen %nation% &enation."
    nation-changed-too-often: "&eYou have switched your nation 3 times already."
    target-nation-leader: "&cThe targetted player is a Nation leader."
    target-rogue: "&cThe targetted player is a rogue player."
    tribe-no-home: "&cYour tribe does not have a home set!"
    unknown-tribe-command: "&cUnknown command! Try /tribe help"
    
    plot-no-plot: "&cYou do not have a plot!"
    plot-sold: "&eYou have sold a plot."
    plot-sethome-success: "&eYou have defined your home."
    plot-sethome-fail: "&cYou can't set your home outside your plot!"
    plot-sethome-fail: "&cYou can't set your home outside your plot!"
    no-buy-other-nation-plot: "&cYou can't buy a plot from another nation!"
    already-have-plot: "&cYou already have a plot!"
    already-sold-plot: "&cThis plot already belongs to someone!"
    not-enough-buy-plot: "&cYou don't have the money to make this purchase!"
    buy-plot-success: "&eYou have purchased a plot."
        
